server:
  port: 8080
spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: master-client-1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    