server:
  port: 8081
spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: master-client-2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      base-path: /customPath
      exposure:
        include: "*"
